version: "3"
services:
  fastapi:
    image: fastapi
    container_name: myfastapi
    build: 
        context: .  
        dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - "./app:/code/app"    